# Generated by Django 5.0.3 on 2024-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_delete_comments_delete_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=255, verbose_name='Имя вашего блога')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='blogs/', verbose_name='Фото блога')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Блоги пользователя',
                'verbose_name_plural': 'Блоги пользователей',
            },
        ),
        migrations.CreateModel(
            name='PersentShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_thing', models.CharField(max_length=255, verbose_name='Какие библиотеки или фреймфорки он знает')),
                ('persent', models.CharField(max_length=255, verbose_name='На сколько процентов знает')),
                ('logo', models.ImageField(upload_to='persent_show/', verbose_name='Логотип фреймфорка')),
            ],
            options={
                'verbose_name': 'Фреймфорки и скилы пользователя',
                'verbose_name_plural': 'Фреймфорки и скилы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('type_job', models.CharField(max_length=255, verbose_name='Имя проекта')),
                ('image', models.ImageField(upload_to='project/')),
                ('description', models.TextField(verbose_name='Коротко о проекте')),
            ],
        ),
        migrations.DeleteModel(
            name='Android',
        ),
        migrations.DeleteModel(
            name='Backend',
        ),
        migrations.DeleteModel(
            name='Desinger',
        ),
        migrations.DeleteModel(
            name='Frontend',
        ),
    ]
