# Generated by Django 5.0.3 on 2024-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_blogs_persentshow_projects_delete_android_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Мои проекты', 'verbose_name_plural': 'Мои проекты'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='type_job',
            field=models.CharField(max_length=255, verbose_name='Какой тип работы'),
        ),
    ]
