# Generated by Django 5.0.1 on 2024-04-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_alter_projects_options_alter_projects_type_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Мои блоги', 'verbose_name_plural': 'Мои блоги'},
        ),
        migrations.AlterModelOptions(
            name='persentshow',
            options={'verbose_name': 'Фреймфорки и скилы я знаю', 'verbose_name_plural': 'Фреймфорки и скилы я знаю'},
        ),
        migrations.AlterModelOptions(
            name='secondary',
            options={'verbose_name': 'Доп информации', 'verbose_name_plural': 'Доп информации'},
        ),
    ]
