# Generated by Django 5.0.3 on 2024-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_blogs_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='PersentShow',
        ),
        migrations.DeleteModel(
            name='Secondary',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Мое оброзование', 'verbose_name_plural': 'Мое оброзование'},
        ),
        migrations.AlterModelOptions(
            name='myservice',
            options={'verbose_name': 'Мои услуги', 'verbose_name_plural': 'Мои услуги'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Мой опыт', 'verbose_name_plural': 'Мой опыт'},
        ),
        migrations.AlterField(
            model_name='myservice',
            name='aboutproj',
            field=models.CharField(max_length=255, verbose_name='Коротко как я делает роботу'),
        ),
    ]
