# Generated by Django 5.0.1 on 2024-04-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_delete_blogs_delete_persentshow_delete_secondary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователя'},
        ),
    ]
